[project]
name = "rag-mcp-server"
version = "0.1.0"
description = "MCP server for RAG on arbitrary files"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.10.1",
    "mcp[cli]>=1.10.1",
    "ruff>=0.11.8",
]
